<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>AtResourceGraph.Reader</AssemblyName>
    <RootNamespace>AtResourceGraph.Reader</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtResourceGraph.AppView.Contracts\AtResourceGraph.AppView.Contracts.csproj" />
  </ItemGroup>
</Project>
